name: Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+*'

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu make

      - name: Build ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            make clean && make
            mv scom scom-linux-x86_64
          else
            make clean && make CC=aarch64-linux-gnu-gcc
            mv scom scom-linux-arm64
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: scom-${{ matrix.arch }}
          path: scom-linux-*

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List built files
        run: ls -R ./artifacts

      - name: Upload GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          files: ./artifacts/**/*

